version: '3'
services:
  cpservice:
    image: CP_IMAGE_NAME
    environment:
      db_details: DETAILS
    deploy:
      placement:
        constraints:
          - node.hostname == NODE
    ports:
      - "8090:8080"
    networks:
      frontend:
        aliases:
          - cpserver
    extra_hosts:
      - "dbserver:IP"
    depends_on:
      - omservice
    command: >
      sh -c "
       /wait-for-it.sh
       "
  omservice:
    image: OM_IMAGE_NAME
    volumes:
      - /home/ubuntu/swarm-docker/test:/mock_mapping
    environment:
      - RUNNING_PORT=38080
    deploy:
      placement:
        constraints:
          - node.hostname == NODE
    networks:
      frontend:
        aliases:
            - omserver

networks:
  frontend:

