version: '3'
services:
  robot:
    env_file: .env
    container_name: ${robot_container_name}
    build:
      context: .
      dockerfile: RFW/Dockerfile
    image: ${robot_image_name}
    volumes:
      - /home/robot/${robot_result_folder}:/robotframework-databaselibrary-1.0.1
    networks:
      frontend:
        aliases:
          - robotsever
    depends_on:
      - cpservice
    command: >
      /bin/bash -c "
        /run.sh
        "
  cpservice:
    env_file: .env
    container_name: ${cp_container_name}
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
      args:
        jarfile_name: ${jarfile_name}
        port: ${port}
        db_details: ${db_details}
    image: ${cp_image_name}
    networks:
      frontend:
        aliases:
          - cpserver
    extra_hosts:
      - "dbserver:52.67.80.187"
    depends_on:
      - omservice
    command: >
      sh -c "
       /wait-for-it.sh
       "
  omservice:
    env_file: .env
    container_name: ${om_container_name}
    build:
      context: .
      dockerfile: mock/Dockerfile
    image: ${om_image_name}
    volumes:
      - ./mock/OM/:/mock_mapping
    environment:
      - RUNNING_PORT=38080
    networks:
      frontend:
        aliases:
            - omserver

networks:
  frontend:

