version: '3'
services:
  cpservice:
    image: CPIMAGE
    environment:
      db_details: DBPASSWORD
    deploy:
      placement:
        constraints:
          - node.hostname == SERVERIP
    ports:
      - "CPPORT:8080"
    networks:
      frontend:
        aliases:
          - cpserver
    extra_hosts:
      - "dbserver:DBIP"
    depends_on:
      - omservice
    command: >
      sh -c "
       /wait-for-it.sh
       "
  omservice:
    image: OMIMAGE
    volumes:
      - /home/ubuntu/swarm-docker/test:/mock_mapping
    environment:
      - RUNNING_PORT=38080
    deploy:
      placement:
        constraints:
          - node.hostname == SERVERIP
    networks:
      frontend:
        aliases:
            - omserver

networks:
  frontend:
